In [85]:
import numpy as np
a=[1,2,3]
#np方式加载py数组
b=np.array(a)
b

a=np.array([1,2,3],float)
a

array([1., 2., 3.])

In [86]:
#多维数组
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
#np创建特殊数组 使用zeros占位符创建数组函数
a=np.zeros((3,3),dtype=int)
a
#全为1的数组：
b=np.ones((3,3),dtype=int)*2
b
#等差数列
c=np.arange(1,10,0.5)
c
#单位矩阵（主对角线为1）
d=np.eye(5)
d
#生成n个在0-1之间平均分布
e=np.random.random(5)
e
#生成n个符合正态分布的随机数组，指定均值为0，标准差0.1
mu,sigma=0,0.1
r_n=np.random.normal(mu,sigma,5)
r_n


array([ 0.13472978, -0.09534831,  0.34950078,  0.09146615, -0.05541212])

In [88]:
#np数组访问
a = np.array([(1,2), (3,4), (5,6)])
#array([1, 2])
a[0]
#从index=1的位置开始到数组结束 array([[3, 4],[5, 6] )
a[1:]
#对数组 a 进行切片,[start:stop:step],a[: , :1] 则为遍历第一维（行），每一行到index<1结束，也就是第一个元素，步长默认1，因此获取每行的第一个元素
aa = np.array([(1,2,3,4), (3,4,5,6), (5,6,7,8)])
print(aa[: , :1])
#行操作
print("aa元素为:\n",aa)
print("所有行,1<=index<3的所有列,步长1\n",aa[:,1:3:1])

[[1]
 [3]
 [5]]
aa元素为:
 [[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]]
所有行,1<=index<3的所有列,步长1
 [[2 3]
 [4 5]
 [6 7]]


In [89]:
#数组遍历
a = np.array([(1,2), (3,4), (5,6)])
for i,j in a:
    print(i+j)

3
7
11


NumPy 数组的常⽤属性

In [90]:
#numpy数组常用属性
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
#ndarray.ndim : 数组的维度（数组轴的个数），等于秩
print("ndim:", a.ndim)
# ndarray.shape : 数组的⼤⼩。为⼀个表⽰数组在每个维度上⼤⼩的整数元组。例如⼆维数组中，表⽰数组的’ ⾏数’ 和’ 列数”
print("shape:", a.shape)
# ndarray.size : 数组元素的总个数，等于 shape 属性中元组元素的乘积
print("size", a.size)
# ndarray.dtype : 表⽰数组中元素类型的对象
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int64


# NumPy 数组的基本操作

In [91]:
# in :检测数值是否在数组中
a = np.array([(1,2), (3,4)])
print(3 in a)
print(5 in a)

True
False


In [92]:
# reshape : 数组的重排列，例如将⼀个 3 维数组转变为 1 维（元素数⼀定要保持不变）
a = np.zeros([2,3,4])
a
a.reshape(24)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [93]:
# tanspose ：转置 (可以直接.T）
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("a=>",a)
a.transpose()

a=> [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [94]:
# flatten : 把多维数组转换为⼀维数组，注意每个元组的⻓度是相同的
a = np.array([(1,2), (3,4), (5,6)])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [98]:
#newaxis : 增加维度
a = np.array([1,2,3])
a.shape
a = a[ :, np.newaxis]
a
a.shape

(3, 1)

# NumPy 数组的数学操作

In [ ]:
# * 星乘表⽰矩阵内各对应位置相乘，点乘表⽰求矩阵内积，⼆维数组称为矩阵积
# （mastrix product）：
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
a = np.array([1,2,1])
#求和 a=4
a.sum()
#求乘积a=2
a.prod()

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]


In [ ]:
# 平均数，⽅差，标准差，最⼤值，最⼩值
a = np.array([5,3,1])
print("mean:",a.mean())
#方差
print("var:", a.var())
#标准差
print("std:", a.std())
print("max:", a.max())
print("min:", a.min())

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452
max: 5
min: 1


In [ ]:
# 最⼤与最⼩值对应的索引值：argmax,argmin:
# 取元素值上限，下限，四舍五⼊：ceil, floor, rint
a = np.array([1.2, 3.8, 4.9])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))
#排序sort
a = np.array([16,31,12,28,22,31,48])
a.sort()
# 除了上述函数外，还有很多数据运算操作，它们的使⽤⽅式基本都类似，例如：abs,
# sign, sqrt, log,log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh,
# arcsinh, arccosh,arctanh 等等。

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


# NumPy 线性代数

In [104]:
# 有关线性代数的运算均在 numpy.linalg 中
# dot : 矩阵乘法，对于两个⼀维的数组，计算的是这两个数组对应下标元素的乘积和
# (数学上称之为内积)；
# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]] , dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]] , dtype=np.float32)
# 使⽤ np.dot 进⾏矩阵乘法
result_dot = np.dot(m1, m2)
# 使⽤ @ 运算符进⾏矩阵乘法
result_at = m1 @ m2
print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使⽤ np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
 # 中层循环：遍历 matrix2 的每⼀列
 # j 表⽰结果矩阵的列索引
 for j in range(m2.shape[1]):
 # 初始化当前位置的结果为 0
    manual_result[i, j] = 0
 # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
 # k 表⽰参与乘法运算的元素索引
    for k in range(m1.shape[1]):
 # 打印当前正在计算的元素
        print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
 # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
        manual_result[i, j] += m1[i, k] * m2[k, j]
 # 打印当前位置计算完成后的结果
 print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
print("⼿动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使⽤ np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

⼿动推演结果:
[[19. 22.]
 [43. 50.]]


In [ ]:
# 还有⼀些函数可以使⽤，
# eig : 特征值、特征向量
# inv : 逆
# qr :QR 分解
# svd : 奇异值分解
# solve : 解线性⽅程 Ax=b 
# lstsq : 计算Ax=b 的最⼩⼆乘解

# ⽂件操作
# ⼆进制⽂件： np.save 、 np.load
# ⽂本⽂件： np.loadtxt 、 np.savetxt
# ⼆进制⽂件会存储为.npy 的格式

In [ ]:
# NumPy ⼴播机制
#当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
a = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b = np.array([-1,1]) # shape(,2)-> shape(1,2) -> shape(4,2) [ -1,1],[-1,1],[-1,1],[-1,1]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])