#张量Tensor

In [1]:
import torch
import numpy as np
data = [ 1, 2],[3, 4]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [2]:
#从 NumPy 数组
np_array = np.array(data)
print(type(np_array))
x_np = torch.from_numpy(np_array)
print("x_np:",x_np)

<class 'numpy.ndarray'>
x_np: tensor([[1, 2],
        [3, 4]])


In [3]:
x_ones = torch.ones_like(x_data) # 保留of x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖 x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0800, 0.5594],
        [0.5067, 0.9433]]) 



In [4]:
shape = (3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8557, 0.9500, 0.4287, 0.0974],
        [0.2706, 0.8924, 0.8717, 0.8071],
        [0.0472, 0.9018, 0.3577, 0.1999]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
# 获取tensor的⼤⼩
# print(m.size()) # torch.Size([5,3])
# print(m.type())
# print(n.size()) 
# print(n.type())

# 均匀分布
a1=torch.rand(5,3)
# 标准正态分布
a2=torch.randn(5,3)
# 离散正态分布
a3=torch.normal(mean=.0,std=1.0,size=(5,3))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
a4=torch.linspace(start=1,end=10,steps=20)
print(a1,"\n",a2,"\n",a3,"\n",a4)

tensor([[0.0276, 0.7917, 0.0796],
        [0.0345, 0.3727, 0.9845],
        [0.8195, 0.9291, 0.6054],
        [0.8002, 0.8742, 0.5369],
        [0.2782, 0.5006, 0.0310]]) 
 tensor([[-0.7239, -2.7178, -1.7371],
        [ 0.2846, -0.4810,  0.2214],
        [ 0.5286,  1.4332, -1.4952],
        [-1.6578, -1.0025,  0.6062],
        [-0.7887,  0.1396, -2.9089]]) 
 tensor([[ 0.2358,  0.2369,  0.6932],
        [-0.3561, -1.0838,  0.8161],
        [-1.8045,  1.8848,  0.3255],
        [-0.2777,  0.3081, -0.3373],
        [-0.2259, -0.6845,  0.2479]]) 
 tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


<!-- 张量的属性
张量的属性描述了张量的形状、数据类型和存储它们的设备。以对象的⻆度来判断，
张量可以看做是具有特征和⽅法的对象。 -->

In [6]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
# 设置张量在GPU上运算
if torch.cuda.is_available():
 tensor = tensor.to('cuda')
# 检查 MPS 是否可用
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    print("MPS 可用，可以使用 M 系列芯片的 GPU")
else:
    print("MPS 不可用，只能使用 CPU")

MPS 可用，可以使用 M 系列芯片的 GPU


In [8]:
#张量的索引和切⽚：
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
#这里...理解不是特别透彻，目前理解:是做切片操作，...是维度操作，在二维的张量下结果一样，但是更高维度结果不一样
print('Last column:', tensor[..., -1])
#对所有行的，index为1的列操作 
# : 表示选取第一维的所有元素，-1 表示在第二维上选取最后一个元素
#... 会代表前面所有的维度
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# 可以使⽤ torch.cat ⽤来连接指定维度的⼀系列张量。另⼀个和 torch.cat 功能类似的函数
# 是torch.stack
#tensor原本是4,4 dim=1在第一个维度上拼接，则拼接为4,12
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
#stack是张量堆叠，原本4,4 3个张量在第一个维度上堆叠后为4,3,4
t1 = torch.stack([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [10]:
# 计算两个张量之间矩阵乘法的⼏种⽅式。 y1, y2, y3 最后的值是⼀样的 dot
print(f"${tensor}")
print(f"tensorT${tensor.T}")
y1 = tensor @ tensor.T
print(f"${y1}")
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

$tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensorT$tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
$tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [11]:
# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [12]:
# 单元素张量
# 如果⼀个单元素张量，例如将张量的值聚合计算，可以使⽤ item() ⽅法将其转换为
# Python 数值
print(f"{tensor}")
agg = tensor.sum()
print(f"{agg}")
print(type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
12.0
<class 'torch.Tensor'>
12.0 <class 'float'>


In [13]:
# In-place操作
# 把计算结果存储到当前操作数中的操作就称为就地操作。含义和pandas中inPlace参
# 数的含义⼀样。pytorch中，这些操作是由带有下划线 _ 后缀的函数表⽰。例如：
# x.copy_(y) ,  x.t_() , 将改变 x ⾃⾝的值。
print(tensor, "\n")
tensor.add_(10)
print(tensor)
#这方法执行后竟然相当于全局变量，每执行一次都在累加。与numpy之间的转换CPU 和 NumPy 数组上的张量共享底层内存位置，所以改变⼀个另⼀个也会变。


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


In [14]:
#张量到numpy数组
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
#数组到张量
s=torch.from_numpy(n)
print(f"s: {s}")
#NumPy 数组的变化也反映在张量中。
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")
print(f"n: {s}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
s: tensor([1., 1., 1., 1., 1.])
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
n: tensor([2., 2., 2., 2., 2.])


In [ ]:
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
#requires_grad（可选）：一个布尔值，用于指定是否需要对该张量进行梯度计算，默认值为 False
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
print(type(result))
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

<class 'torch.Tensor'>


/var/folders/j7/jk94b4xn57g1p5gbnv0z33080000gp/T/ipykernel_3044/4028248882.py:9: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3729.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression2.png'